version: 2
updates:      
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/application/backend/api/src" # Location of package manifests
    schedule:
      interval: "daily"
